name: Build Iris Plugin

on:
  workflow_dispatch:  
  push:
    branches:
      - main
    paths-ignore:    
      - '**.md'
      - '.gitignore'
      - '.github/dependabot.yml'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4    
      with:
        fetch-depth: 0    

    - name: Set up JDK 21
      uses: actions/setup-java@v4  
      with:
        java-version: '21'
        distribution: 'temurin'    
        cache: gradle    

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        cache-read-only: false

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew iris --no-daemon    

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4    
      with:
        name: Iris-${{ github.sha }}
        path: build/libs/*.jar
        retention-days: 30    
        if-no-files-found: error   

    - name: Generate build report
      if: always()    
      uses: actions/upload-artifact@v4
      with:
        name: build-report-${{ github.sha }}
        path: |
          build/reports/
          build/test-results/
        retention-days: 14
